grafana:
  enabled: true
  adminPassword: prom-operator

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - monitoring.test
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: test-tls
        hosts:
          - monitoring.test

prometheus:
  ingress:
    enabled: false
  prometheusSpec:
    scrapeInterval: 5s
    evaluationInterval: 5s
    ruleNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: Exists
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: Exists
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: Exists
    retention: "90d"

alertmanager:
  ingress:
    enabled: false

# Reduce resource usage for local
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi
