grafana:
  enabled: true
  adminPassword: prom-operator

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - monitoring.test
    paths:
      - /
    pathType: Prefix
    tls:
      - secretName: test-tls
        hosts:
          - monitoring.test

prometheus:
  ingress:
    enabled: false

alertmanager:
  ingress:
    enabled: false

# Reduce resource usage for local
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi
