apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-service-monitor
  namespace: api
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: api
  namespaceSelector:
    matchNames:
      - api
  endpoints:
  - port: http
    path: "/metrics"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: images-service-monitor
  namespace: images
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: images
  namespaceSelector:
    matchNames:
      - images
  endpoints:
  - port: http
    path: "/metrics"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-monitor
  namespace: auth
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: auth
  namespaceSelector:
    matchNames:
      - auth
  endpoints:
  - port: http
    path: "/metrics"
