receivers:
  otlp:
    protocols:
      http:

processors:
  batch: {}
  memory_limiter:
    check_interval: 1s
    limit_mib: 400
    spike_limit_mib: 100

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]  # ← also missing this if metrics are expected
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo]  # ← Add this line!
  telemetry:
    logs:
      level: "debug"  # ← Add this line to enable debug logging for the collector
