apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-deployment
  namespace: images
  labels:
    app: images
spec:
  replicas: 2
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
      - name: images
        image: random9deploy/images-service:4
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "postgres-service.db.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-creds
              key: POSTGRES_PASSWORD
        - name: DB_NAME
          value: "api"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
