apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-deployment
  namespace: images
  labels:
    app: images
spec:
  replicas: 2
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      containers:
      - name: images
        image: random9deploy/images-service:8
        ports:
        - containerPort: 8080
        env:
        - name: BUCKET_NAME
          value: "sre-images-bucket"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/gcs/credentials.json
        - name: FLASK_DEBUG
          value: "false"
        volumeMounts:
        - name: gcs-creds
          mountPath: /etc/gcs
          readOnly: true
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m" 
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
      volumes:
      - name: gcs-creds
        secret:
          secretName: gcs-creds
      
