apiVersion: v1
kind: Service
metadata:
  name: images-service
  namespace: images
  labels:
    app: images
spec:
  selector:
    app: images
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
