global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:9464']

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:8080']

  - job_name: 'images'
    static_configs:
      - targets: ['images:8080']

  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres:5432']
  #   metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: 'otel-collector-metrics'
    static_configs:
      - targets: ['otel-collector:8889']