global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:9464']

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:8080']

  - job_name: 'images'
    static_configs:
      - targets: ['images:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics