{
 "title": "Express.js Node Application Application Performance Dashboard",
 "description": "Grafana Dashboard for Node.js Express App with Prometheus Metrics\r\nThis guide explains how to integrate Prometheus monitoring into a Node.js Express application using the prom-client library and visualize the collected metrics in Grafana. The solution leverages the express-prom-bundle middleware to expose key Prometheus metrics such as request duration, uptime, and more.\r\nGrafana Dashboard\r\nTo visualize the Prometheus metrics, Grafana is used to create dashboards that display the following:\r\n\r\nRequest Latency: Visualize HTTP request latency over time, helping you understand performance.\r\nApplication Health: Track the health of the application by monitoring the up metric.\r\nRequest Status Breakdown: View the breakdown of HTTP requests by status code, method, and path to identify potential bottlenecks or issues in the server's routing.\r\nWith this integration, you can easily monitor the health and performance of your Node.js Express application in a Grafana dashboard, powered by Prometheus as the data source.",
 "tags": [
  "app-metrics",
  "performance",
  "monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage (Total)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(my_app_process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "HTTP Response Time Distribution(Sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "http_response_time_seconds_bucket/10000",
     "legendFormat": "{{route}} - Response Time"
    }
   ]
  },
  {
   "title": "Memory Usage (Resident)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "my_app_process_resident_memory_bytes",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "seconds" } },
   "targets": [
    {
     "expr": "rate(my_app_nodejs_gc_duration_seconds_sum{kind='major'}[$__rate_interval])",
     "legendFormat": "Major GC"
    }
   ]
  },
  {
   "title": "Active Resources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "my_app_nodejs_active_resources_total",
     "legendFormat": "Active Resources"
    }
   ]
  },
  {
   "title": "HTTP Active Request Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "my_app_nodejs_active_handles_total",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Heap Size Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "my_app_nodejs_heap_size_used_bytes",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "my_app_nodejs_heap_size_total_bytes",
     "legendFormat": "Total Heap"
    }
   ]
  },
  {
   "title": "Event Loop Lag (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "my_app_nodejs_eventloop_lag_seconds",
     "legendFormat": "Event Loop Lag"
    }
   ]
  }
 ]
}